### ISSUE TITLE
The 3DChameleon isn't open source

### ISSUE THREAD

**Issue by wjsteele** [apoorv1in/TetraFlow_MMU#2]
Man, I hate to do this, but I designed this and released it so my customers could upgrade their older machines, or home users could print and use the files themselves.  It wasn't published as an open source license intentionally to protect my small business.  I do this as a hobby and I quite often release technologies into the open source world (like belt printers, for example), but some of the key elements here are unique to my design and cost advantage over other systems. When the time is appropriate, I will release them in the future, but this version isn't ready for that yet as it's the latest design my business model is built around.

Please read the license carefully.  CC BY-NC-ND 4.0 means you can make them for yourself, but you can't publish derivatives of the works.

This is a snippet from the license:

You are free to:
Share — copy and redistribute the material in any medium or format
  The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:
  Attribution — You must give [appropriate credit ](https://creativecommons.org/licenses/by-nc-nd/4.0/#ref-appropriate-credit), provide a link to the license, and [indicate if changes were made ](https://creativecommons.org/licenses/by-nc-nd/4.0/#ref-indicate-changes). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
  Non Commercial — You may not use the material for [commercial purposes ](https://creativecommons.org/licenses/by-nc-nd/4.0/#ref-commercial-purposes).
  No Derivatives — If you [remix, transform, or build upon ](https://creativecommons.org/licenses/by-nc-nd/4.0/#ref-some-kinds-of-mods)the material, you may not distribute the modified material.
  No additional restrictions — You may not apply legal terms or [technological measures ](https://creativecommons.org/licenses/by-nc-nd/4.0/#ref-technological-measures)that legally restrict others from doing anything the license permits.

Bill

**Comment by Jomik** [comment]
Just a curious comment here, but unless they've gotten access to your CAD and modified that, or code, then this is in no way infringing on your copyright.
Gaining inspiration from projects is not an indication that it's a derivative..
Your license applies to the files you share, not the idea.

Please do not hinder progress and development in our 3d printer community with these claims.
The only way you can protect your mechanism in the 3dchameleon is by attempting to patent it.

**Comment by yeorinhieut** [comment]
Bill,

While I understand your desire to protect your intellectual property, your stance on this matter seems overly restrictive and narrow-minded.

It's important to clarify that dothediy did not directly use your CAD files. He merely drew inspiration from the concept and recreated it independently. This does not constitute a violation of the CC BY-NC-ND 4.0 license. Conceptual inspiration is fundamentally different from creating derivative works.

Innovation often builds upon existing ideas. Attempting to stifle this natural progression seems counterproductive to the spirit of technological advancement.

A more open and collaborative approach would likely benefit both your business and the wider maker community. Instead of unwarranted restrictions and accusations, let's foster an environment that encourages creativity and collaboration.
